// tools/build-assets.mjs
//
// 1. shaders/*.glsl          -> src/shaders/generated.js
// 2. config.json             -> src/config.generated.js
//
// Both source files are the single source of truth: the browser build and the
// single-file distribution import the same generated modules, so there is no
// chance of the dev and shipped configurations drifting apart.
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { execFileSync } from 'node:child_process';

const ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..');
const SHADER_SRC = path.join(ROOT, 'shaders');

/* ---------------------------------------------------------------- shaders */
const cache = new Map();
function readShader(name) {
  if (cache.has(name)) return cache.get(name);
  const p = path.join(SHADER_SRC, name + '.glsl');
  if (!fs.existsSync(p)) throw new Error('shader not found: ' + p);
  let src = fs.readFileSync(p, 'utf8');
  src = src.replace(/^[ \t]*#include\s+"([^"]+)"\s*$/gm, (_, inc) => readShader(inc));
  cache.set(name, src);
  return src;
}

function splitStages(src, file) {
  const vStart = src.indexOf('#ifdef VERTEX');
  const fStart = src.indexOf('#ifdef FRAGMENT');
  if (vStart < 0 || fStart < 0) throw new Error(file + ': missing VERTEX/FRAGMENT guard');
  const afterV = src.indexOf('\n', vStart) + 1;
  const vEnd = src.lastIndexOf('#endif', fStart);
  const afterF = src.indexOf('\n', fStart) + 1;
  const fEnd = src.lastIndexOf('#endif');
  if (vEnd < afterV || fEnd < afterF) throw new Error(file + ': malformed stage guards');
  // Everything above the first guard — i.e. the inlined `common` block with the
  // shared uniforms and helpers — belongs to BOTH stages. Dropping it is how the
  // shaders ended up unable to see uTime, uSunDir or hash13.
  const preamble = src.slice(0, vStart).trim();
  return {
    vertex: (preamble + '\n\n' + src.slice(afterV, vEnd).trim()) + '\n',
    fragment: (preamble + '\n\n' + src.slice(afterF, fEnd).trim()) + '\n',
  };
}

const files = fs.readdirSync(SHADER_SRC).filter((f) => f.endsWith('.glsl') && f !== 'common.glsl');
const shaders = {};
for (const f of files) {
  const name = path.basename(f, '.glsl');
  const stages = splitStages(readShader(name), f);
  // sanity: every uniform the shader declares must exist in the shared block
  for (const stage of [stages.vertex, stages.fragment]) {
    if (/\buOccColor\b/.test(stage) && !/uniform vec3\s+uOccColor/.test(stage)) {
      throw new Error(`${name}: uOccColor used but not declared`);
    }
  }
  shaders[name] = stages;
}

const shaderOut =
  `// AUTO-GENERATED by tools/build-assets.mjs — do not edit by hand.\n` +
  `// Source of truth: shaders/*.glsl\n\n` +
  `export const SHADERS = {\n` +
  Object.entries(shaders).map(([k, v]) =>
    `  ${JSON.stringify(k)}: {\n    vertex: ${JSON.stringify(v.vertex)},\n    fragment: ${JSON.stringify(v.fragment)},\n  },`).join('\n') +
  `\n};\n\nexport const SHADER_NAMES = ${JSON.stringify(Object.keys(shaders))};\n`;

fs.mkdirSync(path.join(ROOT, 'src', 'shaders'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'src', 'shaders', 'generated.js'), shaderOut);

/* ----------------------------------------------------------------- config */
const cfg = JSON.parse(fs.readFileSync(path.join(ROOT, 'config.json'), 'utf8'));
const cfgOut =
  `// AUTO-GENERATED from config.json by tools/build-assets.mjs — do not edit by hand.\n` +
  `export default ${JSON.stringify(cfg, null, 2)};\n`;
fs.writeFileSync(path.join(ROOT, 'src', 'config.generated.js'), cfgOut);

const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(1) + ' KB';
console.log(`build-assets: shaders [${Object.keys(shaders).join(', ')}] ${kb(shaderOut)}`);
console.log(`build-assets: config ${kb(cfgOut)}`);

// docs/CONFIG.md is generated from the same JSON in the same run, so the
// reference can never drift from the thing it documents.
execFileSync(process.execPath, [path.join(ROOT, 'tools', 'make-config-doc.mjs')], { stdio: 'inherit' });
